// 单词音标和释义数据
// 格式: { phonetic: 音标, definition: 释义 }
const wordInfo = {
  // Level 1 - Alphabet & Sounds
  apple: { phonetic: '/ˈæpl/', definition: 'n. 苹果' },
  ant: { phonetic: '/ænt/', definition: 'n. 蚂蚁' },
  alligator: { phonetic: '/ˈælɪɡeɪtə/', definition: 'n. 短吻鳄' },
  ball: { phonetic: '/bɔːl/', definition: 'n. 球' },
  bee: { phonetic: '/biː/', definition: 'n. 蜜蜂' },
  banana: { phonetic: '/bəˈnɑːnə/', definition: 'n. 香蕉' },
  cat: { phonetic: '/kæt/', definition: 'n. 猫' },
  cup: { phonetic: '/kʌp/', definition: 'n. 杯子' },
  cake: { phonetic: '/keɪk/', definition: 'n. 蛋糕' },
  dog: { phonetic: '/dɒɡ/', definition: 'n. 狗' },
  duck: { phonetic: '/dʌk/', definition: 'n. 鸭子' },
  door: { phonetic: '/dɔː/', definition: 'n. 门' },
  egg: { phonetic: '/eɡ/', definition: 'n. 鸡蛋' },
  elephant: { phonetic: '/ˈelɪfənt/', definition: 'n. 大象' },
  ear: { phonetic: '/ɪə/', definition: 'n. 耳朵' },
  fish: { phonetic: '/fɪʃ/', definition: 'n. 鱼' },
  frog: { phonetic: '/frɒɡ/', definition: 'n. 青蛙' },
  flower: { phonetic: '/ˈflaʊə/', definition: 'n. 花' },
  goat: { phonetic: '/ɡəʊt/', definition: 'n. 山羊' },
  gift: { phonetic: '/ɡɪft/', definition: 'n. 礼物' },
  gorilla: { phonetic: '/ɡəˈrɪlə/', definition: 'n. 大猩猩' },
  hat: { phonetic: '/hæt/', definition: 'n. 帽子' },
  horse: { phonetic: '/hɔːs/', definition: 'n. 马' },
  house: { phonetic: '/haʊs/', definition: 'n. 房子' },
  igloo: { phonetic: '/ˈɪɡluː/', definition: 'n. 冰屋' },
  ink: { phonetic: '/ɪŋk/', definition: 'n. 墨水' },
  island: { phonetic: '/ˈaɪlənd/', definition: 'n. 岛屿' },
  jam: { phonetic: '/dʒæm/', definition: 'n. 果酱' },
  jump: { phonetic: '/dʒʌmp/', definition: 'v. 跳' },
  juice: { phonetic: '/dʒuːs/', definition: 'n. 果汁' },
  kite: { phonetic: '/kaɪt/', definition: 'n. 风筝' },
  king: { phonetic: '/kɪŋ/', definition: 'n. 国王' },
  koala: { phonetic: '/kəʊˈɑːlə/', definition: 'n. 考拉' },
  lion: { phonetic: '/ˈlaɪən/', definition: 'n. 狮子' },
  lamp: { phonetic: '/læmp/', definition: 'n. 台灯' },
  lemon: { phonetic: '/ˈlemən/', definition: 'n. 柠檬' },
  monkey: { phonetic: '/ˈmʌŋki/', definition: 'n. 猴子' },
  milk: { phonetic: '/mɪlk/', definition: 'n. 牛奶' },
  moon: { phonetic: '/muːn/', definition: 'n. 月亮' },
  nest: { phonetic: '/nest/', definition: 'n. 鸟巢' },
  nose: { phonetic: '/nəʊz/', definition: 'n. 鼻子' },
  net: { phonetic: '/net/', definition: 'n. 网' },
  octopus: { phonetic: '/ˈɒktəpəs/', definition: 'n. 章鱼' },
  owl: { phonetic: '/aʊl/', definition: 'n. 猫头鹰' },
  orange: { phonetic: '/ˈɒrɪndʒ/', definition: 'n. 橙子' },
  pizza: { phonetic: '/ˈpiːtsə/', definition: 'n. 披萨' },
  pig: { phonetic: '/pɪɡ/', definition: 'n. 猪' },
  pen: { phonetic: '/pen/', definition: 'n. 钢笔' },
  queen: { phonetic: '/kwiːn/', definition: 'n. 女王' },
  quilt: { phonetic: '/kwɪlt/', definition: 'n. 被子' },
  question: { phonetic: '/ˈkwestʃən/', definition: 'n. 问题' },
  rabbit: { phonetic: '/ˈræbɪt/', definition: 'n. 兔子' },
  rose: { phonetic: '/rəʊz/', definition: 'n. 玫瑰' },
  ring: { phonetic: '/rɪŋ/', definition: 'n. 戒指' },
  sun: { phonetic: '/sʌn/', definition: 'n. 太阳' },
  snake: { phonetic: '/sneɪk/', definition: 'n. 蛇' },
  star: { phonetic: '/stɑː/', definition: 'n. 星星' },
  tiger: { phonetic: '/ˈtaɪɡə/', definition: 'n. 老虎' },
  tree: { phonetic: '/triː/', definition: 'n. 树' },
  train: { phonetic: '/treɪn/', definition: 'n. 火车' },
  umbrella: { phonetic: '/ʌmˈbrelə/', definition: 'n. 雨伞' },
  up: { phonetic: '/ʌp/', definition: 'adv. 向上' },
  unicorn: { phonetic: '/ˈjuːnɪkɔːn/', definition: 'n. 独角兽' },
  violin: { phonetic: '/ˌvaɪəˈlɪn/', definition: 'n. 小提琴' },
  van: { phonetic: '/væn/', definition: 'n. 货车' },
  vase: { phonetic: '/vɑːz/', definition: 'n. 花瓶' },
  watch: { phonetic: '/wɒtʃ/', definition: 'n. 手表；v. 观看' },
  whale: { phonetic: '/weɪl/', definition: 'n. 鲸鱼' },
  window: { phonetic: '/ˈwɪndəʊ/', definition: 'n. 窗户' },
  box: { phonetic: '/bɒks/', definition: 'n. 盒子' },
  fox: { phonetic: '/fɒks/', definition: 'n. 狐狸' },
  six: { phonetic: '/sɪks/', definition: 'n. 六' },
  yellow: { phonetic: '/ˈjeləʊ/', definition: 'adj. 黄色的；n. 黄色' },
  yak: { phonetic: '/jæk/', definition: 'n. 牦牛' },
  yoyo: { phonetic: '/ˈjəʊjəʊ/', definition: 'n. 悠悠球' },
  zebra: { phonetic: '/ˈzebrə/', definition: 'n. 斑马' },
  zoo: { phonetic: '/zuː/', definition: 'n. 动物园' },
  zero: { phonetic: '/ˈzɪərəʊ/', definition: 'n. 零' },
  bear: { phonetic: '/beə/', definition: 'n. 熊' },
  iguana: { phonetic: '/ɪˈɡwɑːnə/', definition: 'n. 鬣蜥' },
  jelly: { phonetic: '/ˈdʒeli/', definition: 'n. 果冻' },
  kangaroo: { phonetic: '/ˌkæŋɡəˈruː/', definition: 'n. 袋鼠' },
  mouse: { phonetic: '/maʊs/', definition: 'n. 老鼠' },
  ostrich: { phonetic: '/ˈɒstrɪtʃ/', definition: 'n. 鸵鸟' },
  panda: { phonetic: '/ˈpændə/', definition: 'n. 熊猫' },
  seal: { phonetic: '/siːl/', definition: 'n. 海豹' },
  tent: { phonetic: '/tent/', definition: 'n. 帐篷' },
  'yo-yo': { phonetic: '/ˈjəʊjəʊ/', definition: 'n. 悠悠球' },

  // Level 2 - Unit 2
  fan: { phonetic: '/fæn/', definition: 'n. 风扇；迷' },
  pan: { phonetic: '/pæn/', definition: 'n. 平底锅' },
  can: { phonetic: '/kæn/', definition: 'v. 能；罐头' },
  man: { phonetic: '/mæn/', definition: 'n. 男人' },
  jam: { phonetic: '/dʒæm/', definition: 'n. 果酱' },
  ram: { phonetic: '/ræm/', definition: 'n. 公羊' },
  dad: { phonetic: '/dæd/', definition: 'n. 爸爸' },
  sad: { phonetic: '/sæd/', definition: 'adj. 悲伤的' },
  bag: { phonetic: '/bæɡ/', definition: 'n. 包；袋子' },
  tag: { phonetic: '/tæɡ/', definition: 'n. 标签；v. 贴标签' },
  ham: { phonetic: '/hæm/', definition: 'n. 火腿' },
  dam: { phonetic: '/dæm/', definition: 'n. 水坝' },
  Sam: { phonetic: '/sæm/', definition: 'n. 萨姆（人名）' },
  van: { phonetic: '/væn/', definition: 'n. 货车' },
  bad: { phonetic: '/bæd/', definition: 'adj. 坏的' },
  had: { phonetic: '/hæd/', definition: 'v. 有（过去式）' },
  lad: { phonetic: '/læd/', definition: 'n. 男孩' },
  gag: { phonetic: '/ɡæɡ/', definition: 'v. 捂住嘴' },
  hag: { phonetic: '/hæɡ/', definition: 'n. 女巫' },
  jag: { phonetic: '/dʒæɡ/', definition: 'n. 突出物' },
  cap: { phonetic: '/kæp/', definition: 'n. 帽子' },
  gap: { phonetic: '/ɡæp/', definition: 'n. 缺口' },
  lap: { phonetic: '/læp/', definition: 'n. 膝盖；一圈' },
  map: { phonetic: '/mæp/', definition: 'n. 地图' },
  nap: { phonetic: '/næp/', definition: 'n. 小睡' },
  bat: { phonetic: '/bæt/', definition: 'n. 蝙蝠；球棒' },
  cat: { phonetic: '/kæt/', definition: 'n. 猫' },
  fat: { phonetic: '/fæt/', definition: 'adj. 肥胖的' },
  hat: { phonetic: '/hæt/', definition: 'n. 帽子' },
  mat: { phonetic: '/mæt/', definition: 'n. 垫子' },

  // Unit 3
  bed: { phonetic: '/bed/', definition: 'n. 床' },
  red: { phonetic: '/red/', definition: 'adj. 红色的' },
  wed: { phonetic: '/wed/', definition: 'v. 结婚' },
  peg: { phonetic: '/peɡ/', definition: 'n. 衣夹；钉' },
  leg: { phonetic: '/leɡ/', definition: 'n. 腿' },
  hen: { phonetic: '/hen/', definition: 'n. 母鸡' },
  pen: { phonetic: '/pen/', definition: 'n. 钢笔' },
  ten: { phonetic: '/ten/', definition: 'n. 十' },
  jet: { phonetic: '/dʒet/', definition: 'n. 喷气式飞机' },
  net: { phonetic: '/net/', definition: 'n. 网' },
  bet: { phonetic: '/bet/', definition: 'v. 打赌' },
  get: { phonetic: '/ɡet/', definition: 'v. 得到' },
  let: { phonetic: '/let/', definition: 'v. 让' },
  Ben: { phonetic: '/ben/', definition: 'n. 本（人名）' },
  den: { phonetic: '/den/', definition: 'n. 兽穴；书房' },
  fed: { phonetic: '/fed/', definition: 'v. 喂食（过去式）' },
  led: { phonetic: '/led/', definition: 'v. 带领（过去式）' },

  // Unit 4
  big: { phonetic: '/bɪɡ/', definition: 'adj. 大的' },
  dig: { phonetic: '/dɪɡ/', definition: 'v. 挖' },
  fig: { phonetic: '/fɪɡ/', definition: 'n. 无花果' },
  wig: { phonetic: '/wɪɡ/', definition: 'n. 假发' },
  bin: { phonetic: '/bɪn/', definition: 'n. 垃圾箱' },
  fin: { phonetic: '/fɪn/', definition: 'n. 鱼鳍' },
  pin: { phonetic: '/pɪn/', definition: 'n. 别针' },
  tin: { phonetic: '/tɪn/', definition: 'n. 锡罐' },
  pit: { phonetic: '/pɪt/', definition: 'n. 坑' },
  sit: { phonetic: '/sɪt/', definition: 'v. 坐' },
  hit: { phonetic: '/hɪt/', definition: 'v. 打；击中' },
  kit: { phonetic: '/kɪt/', definition: 'n. 工具箱' },
  six: { phonetic: '/sɪks/', definition: 'n. 六' },
  mix: { phonetic: '/mɪks/', definition: 'v. 混合' },
  fix: { phonetic: '/fɪks/', definition: 'v. 修理' },
  lip: { phonetic: '/lɪp/', definition: 'n. 嘴唇' },
  rip: { phonetic: '/rɪp/', definition: 'v. 撕裂' },
  sip: { phonetic: '/sɪp/', definition: 'v. 小口喝' },
  dip: { phonetic: '/dɪp/', definition: 'v. 蘸' },
  nip: { phonetic: '/nɪp/', definition: 'v. 掐' },
  fit: { phonetic: '/fɪt/', definition: 'adj. 合身的；v. 适合' },
  pig: { phonetic: '/pɪɡ/', definition: 'n. 猪' },
  win: { phonetic: '/wɪn/', definition: 'v. 赢' },
  grin: { phonetic: '/ɡrɪn/', definition: 'v. 咧嘴笑' },
  chin: { phonetic: '/tʃɪn/', definition: 'n. 下巴' },
  spin: { phonetic: '/spɪn/', definition: 'v. 旋转' },
  twin: { phonetic: '/twɪn/', definition: 'n. 双胞胎' },
  slit: { phonetic: '/slɪt/', definition: 'n. 裂缝' },
  knit: { phonetic: '/nɪt/', definition: 'v. 编织' },
  skip: { phonetic: '/skɪp/', definition: 'v. 跳过' },
  hip: { phonetic: '/hɪp/', definition: 'n. 臀部' },
  tip: { phonetic: '/tɪp/', definition: 'n. 尖端；小费' },
  ship: { phonetic: '/ʃɪp/', definition: 'n. 船' },
  chip: { phonetic: '/tʃɪp/', definition: 'n. 薯片；碎片' },
  fish: { phonetic: '/fɪʃ/', definition: 'n. 鱼' },
  dish: { phonetic: '/dɪʃ/', definition: 'n. 盘子' },
  wish: { phonetic: '/wɪʃ/', definition: 'v. 希望' },

  // Unit 5
  hot: { phonetic: '/hɒt/', definition: 'adj. 热的' },
  pot: { phonetic: '/pɒt/', definition: 'n. 锅；罐' },
  lot: { phonetic: '/lɒt/', definition: 'n. 很多' },
  dot: { phonetic: '/dɒt/', definition: 'n. 点' },
  got: { phonetic: '/ɡɒt/', definition: 'v. 得到（过去式）' },
  not: { phonetic: '/nɒt/', definition: 'adv. 不' },
  rot: { phonetic: '/rɒt/', definition: 'v. 腐烂' },
  cot: { phonetic: '/kɒt/', definition: 'n. 简易床' },
  top: { phonetic: '/tɒp/', definition: 'n. 顶部' },
  mop: { phonetic: '/mɒp/', definition: 'n. 拖把' },
  pop: { phonetic: '/pɒp/', definition: 'v. 爆开；n. 汽水' },
  hop: { phonetic: '/hɒp/', definition: 'v. 单脚跳' },
  cop: { phonetic: '/kɒp/', definition: 'n. 警察' },
  fox: { phonetic: '/fɒks/', definition: 'n. 狐狸' },
  box: { phonetic: '/bɒks/', definition: 'n. 盒子' },
  ox: { phonetic: '/ɒks/', definition: 'n. 公牛' },
  job: { phonetic: '/dʒɒb/', definition: 'n. 工作' },
  sob: { phonetic: '/sɒb/', definition: 'v. 啜泣' },
  rob: { phonetic: '/rɒb/', definition: 'v. 抢劫' },
  bob: { phonetic: '/bɒb/', definition: 'v. 上下移动' },
  nod: { phonetic: '/nɒd/', definition: 'v. 点头' },
  rod: { phonetic: '/rɒd/', definition: 'n. 杆子' },
  sod: { phonetic: '/sɒd/', definition: 'n. 草皮' },
  pod: { phonetic: '/pɒd/', definition: 'n. 豆荚' },
  cod: { phonetic: '/kɒd/', definition: 'n. 鳕鱼' },
  jog: { phonetic: '/dʒɒɡ/', definition: 'v. 慢跑' },
  fog: { phonetic: '/fɒɡ/', definition: 'n. 雾' },
  dog: { phonetic: '/dɒɡ/', definition: 'n. 狗' },
  log: { phonetic: '/lɒɡ/', definition: 'n. 原木；日志' },
  cog: { phonetic: '/kɒɡ/', definition: 'n. 齿轮' },
  hog: { phonetic: '/hɒɡ/', definition: 'n. 公猪' },
  frog: { phonetic: '/frɒɡ/', definition: 'n. 青蛙' },
  long: { phonetic: '/lɒŋ/', definition: 'adj. 长的' },
  song: { phonetic: '/sɒŋ/', definition: 'n. 歌曲' },
  bong: { phonetic: '/bɒŋ/', definition: 'n. 水烟筒' },
  gong: { phonetic: '/ɡɒŋ/', definition: 'n. 锣' },

  // Unit 6
  mum: { phonetic: '/mʌm/', definition: 'n. 妈妈' },
  hum: { phonetic: '/hʌm/', definition: 'v. 哼唱' },
  sum: { phonetic: '/sʌm/', definition: 'n. 总和' },
  gum: { phonetic: '/ɡʌm/', definition: 'n. 口香糖' },
  but: { phonetic: '/bʌt/', definition: 'conj. 但是' },
  cut: { phonetic: '/kʌt/', definition: 'v. 切；剪' },
  nut: { phonetic: '/nʌt/', definition: 'n. 坚果' },
  hut: { phonetic: '/hʌt/', definition: 'n. 小屋' },
  shut: { phonetic: '/ʃʌt/', definition: 'v. 关闭' },
  putt: { phonetic: '/pʌt/', definition: 'v. 推球（高尔夫）' },
  bus: { phonetic: '/bʌs/', definition: 'n. 公共汽车' },
  plus: { phonetic: '/plʌs/', definition: 'prep. 加' },
  us: { phonetic: '/ʌs/', definition: 'pron. 我们' },
  fuss: { phonetic: '/fʌs/', definition: 'n. 大惊小怪' },
  fun: { phonetic: '/fʌn/', definition: 'adj. 有趣的' },
  run: { phonetic: '/rʌn/', definition: 'v. 跑' },
  sun: { phonetic: '/sʌn/', definition: 'n. 太阳' },
  bun: { phonetic: '/bʌn/', definition: 'n. 小圆面包' },
  nun: { phonetic: '/nʌn/', definition: 'n. 修女' },
  gun: { phonetic: '/ɡʌn/', definition: 'n. 枪' },
  cup: { phonetic: '/kʌp/', definition: 'n. 杯子' },
  pup: { phonetic: '/pʌp/', definition: 'n. 小狗' },
  mud: { phonetic: '/mʌd/', definition: 'n. 泥土' },
  bud: { phonetic: '/bʌd/', definition: 'n. 芽' },
  dud: { phonetic: '/dʌd/', definition: 'n. 无用物' },
  tub: { phonetic: '/tʌb/', definition: 'n. 浴缸' },
  rub: { phonetic: '/rʌb/', definition: 'v. 摩擦' },
  sub: { phonetic: '/sʌb/', definition: 'n. 潜水艇' },
  bug: { phonetic: '/bʌɡ/', definition: 'n. 昆虫' },
  rug: { phonetic: '/rʌɡ/', definition: 'n. 地毯' },
  jug: { phonetic: '/dʒʌɡ/', definition: 'n. 水壶' },
  mug: { phonetic: '/mʌɡ/', definition: 'n. 马克杯' },
  tug: { phonetic: '/tʌɡ/', definition: 'v. 用力拉' },
  duck: { phonetic: '/dʌk/', definition: 'n. 鸭子' },
  luck: { phonetic: '/lʌk/', definition: 'n. 运气' },
  truck: { phonetic: '/trʌk/', definition: 'n. 卡车' },
  muck: { phonetic: '/mʌk/', definition: 'n. 粪便' },

  // Level 3
  cake: { phonetic: '/keɪk/', definition: 'n. 蛋糕' },
  lake: { phonetic: '/leɪk/', definition: 'n. 湖泊' },
  make: { phonetic: '/meɪk/', definition: 'v. 制作' },
  name: { phonetic: '/neɪm/', definition: 'n. 名字' },
  game: { phonetic: '/ɡeɪm/', definition: 'n. 游戏' },
  same: { phonetic: '/seɪm/', definition: 'adj. 相同的' },
  tame: { phonetic: '/teɪm/', definition: 'adj. 驯服的' },
  fame: { phonetic: '/feɪm/', definition: 'n. 名声' },
  gate: { phonetic: '/ɡeɪt/', definition: 'n. 大门' },
  date: { phonetic: '/deɪt/', definition: 'n. 日期；约会' },
  late: { phonetic: '/leɪt/', definition: 'adj. 迟到的' },
  rate: { phonetic: '/reɪt/', definition: 'n. 比率；速度' },
  mate: { phonetic: '/meɪt/', definition: 'n. 伙伴' },
  take: { phonetic: '/teɪk/', definition: 'v. 拿取' },
  bake: { phonetic: '/beɪk/', definition: 'v. 烘焙' },
  cave: { phonetic: '/keɪv/', definition: 'n. 洞穴' },
  gave: { phonetic: '/ɡeɪv/', definition: 'v. 给（give的过去式）' },
  brave: { phonetic: '/breɪv/', definition: 'adj. 勇敢的' },
  face: { phonetic: '/feɪs/', definition: 'n. 脸' },
  race: { phonetic: '/reɪs/', definition: 'n. 比赛；v. 赛跑' },
  pace: { phonetic: '/peɪs/', definition: 'n. 步伐' },
  case: { phonetic: '/keɪs/', definition: 'n. 箱子；情况' },
  plane: { phonetic: '/pleɪn/', definition: 'n. 飞机' },
  cane: { phonetic: '/keɪn/', definition: 'n. 手杖；甘蔗' },
  wane: { phonetic: '/weɪn/', definition: 'v. 衰减' },
  shape: { phonetic: '/ʃeɪp/', definition: 'n. 形状' },
  grape: { phonetic: '/ɡreɪp/', definition: 'n. 葡萄' },
  drape: { phonetic: '/dreɪp/', definition: 'v. 悬挂' },

  bike: { phonetic: '/baɪk/', definition: 'n. 自行车' },
  like: { phonetic: '/laɪk/', definition: 'v. 喜欢' },
  kite: { phonetic: '/kaɪt/', definition: 'n. 风筝' },
  five: { phonetic: '/faɪv/', definition: 'n. 五' },
  nine: { phonetic: '/naɪn/', definition: 'n. 九' },
  drive: { phonetic: '/draɪv/', definition: 'v. 开车' },
  dive: { phonetic: '/daɪv/', definition: 'v. 潜水' },
  hive: { phonetic: '/haɪv/', definition: 'n. 蜂巢' },
  mime: { phonetic: '/maɪm/', definition: 'n. 哑剧' },
  chime: { phonetic: '/tʃaɪm/', definition: 'n. 钟声；v. 鸣响' },
  pike: { phonetic: '/paɪk/', definition: 'n. 长矛；梭子鱼' },
  alive: { phonetic: '/əˈlaɪv/', definition: 'adj. 活着的' },
  arrive: { phonetic: '/əˈraɪv/', definition: 'v. 到达' },
  thrive: { phonetic: '/θraɪv/', definition: 'v. 繁荣' },
  smile: { phonetic: '/smaɪl/', definition: 'v. 微笑' },
  tile: { phonetic: '/taɪl/', definition: 'n. 瓷砖' },
  pile: { phonetic: '/paɪl/', definition: 'n. 堆' },
  while: { phonetic: '/waɪl/', definition: 'conj. 当...时候' },
  spine: { phonetic: '/spaɪn/', definition: 'n. 脊椎' },
  swine: { phonetic: '/swaɪn/', definition: 'n. 猪' },
  shine: { phonetic: '/ʃaɪn/', definition: 'v. 发光' },
  fine: { phonetic: '/faɪn/', definition: 'adj. 好的' },
  mine: { phonetic: '/maɪn/', definition: 'pron. 我的；n. 矿' },
  wine: { phonetic: '/waɪn/', definition: 'n. 葡萄酒' },
  dine: { phonetic: '/daɪn/', definition: 'v. 进餐' },
  line: { phonetic: '/laɪn/', definition: 'n. 线条' },
 pine: { phonetic: '/paɪn/', definition: 'n. 松树' },
  vine: { phonetic: '/vaɪn/', definition: 'n. 藤蔓' },
  quite: { phonetic: '/kwaɪt/', definition: 'adv. 相当' },
  bite: { phonetic: '/baɪt/', definition: 'v. 咬' },
  site: { phonetic: '/saɪt/', definition: 'n. 地点；网站' },
  write: { phonetic: '/raɪt/', definition: 'v. 写' },
  white: { phonetic: '/waɪt/', definition: 'adj. 白色的' },
  night: { phonetic: '/naɪt/', definition: 'n. 夜晚' },
  right: { phonetic: '/raɪt/', definition: 'adj. 正确的；右边' },
  light: { phonetic: '/laɪt/', definition: 'n. 光；adj. 明亮的' },
  fight: { phonetic: '/faɪt/', definition: 'v. 打架' },
  sight: { phonetic: '/saɪt/', definition: 'n. 视力；景象' },
  flight: { phonetic: '/flaɪt/', definition: 'n. 航班；飞行' },
  slight: { phonetic: '/slaɪt/', definition: 'adj. 轻微的' },
  bright: { phonetic: '/braɪt/', definition: 'adj. 明亮的' },

  home: { phonetic: '/həʊm/', definition: 'n. 家' },
  rope: { phonetic: '/rəʊp/', definition: 'n. 绳子' },
  bone: { phonetic: '/bəʊn/', definition: 'n. 骨头' },
  zone: { phonetic: '/zəʊn/', definition: 'n. 区域' },
  stone: { phonetic: '/stəʊn/', definition: 'n. 石头' },
  phone: { phonetic: '/fəʊn/', definition: 'n. 电话' },
  rose: { phonetic: '/rəʊz/', definition: 'n. 玫瑰' },
  nose: { phonetic: '/nəʊz/', definition: 'n. 鼻子' },
  hose: { phonetic: '/həʊz/', definition: 'n. 软管' },
  dose: { phonetic: '/dəʊs/', definition: 'n. 剂量' },
  joke: { phonetic: '/dʒəʊk/', definition: 'n. 笑话' },
  coke: { phonetic: '/kəʊk/', definition: 'n. 可乐' },
  poke: { phonetic: '/pəʊk/', definition: 'v. 戳' },
  smoke: { phonetic: '/sməʊk/', definition: 'n. 烟雾；v. 抽烟' },
  hope: { phonetic: '/həʊp/', definition: 'v. 希望' },
  scope: { phonetic: '/skəʊp/', definition: 'n. 范围' },
  cone: { phonetic: '/kəʊn/', definition: 'n. 圆锥体' },
  tone: { phonetic: '/təʊn/', definition: 'n. 语气；音调' },
  lone: { phonetic: '/ləʊn/', definition: 'adj. 孤独的' },
  note: { phonetic: '/nəʊt/', definition: 'n. 笔记；音符' },
  vote: { phonetic: '/vəʊt/', definition: 'n. 投票；v. 投票' },
  boat: { phonetic: '/bəʊt/', definition: 'n. 船' },
  coat: { phonetic: '/kəʊt/', definition: 'n. 外套' },
  goat: { phonetic: '/ɡəʊt/', definition: 'n. 山羊' },
  float: { phonetic: '/fləʊt/', definition: 'v. 漂浮' },
  soap: { phonetic: '/səʊp/', definition: 'n. 肥皂' },
  road: { phonetic: '/rəʊd/', definition: 'n. 道路' },
  load: { phonetic: '/ləʊd/', definition: 'n. 负载' },
  toad: { phonetic: '/təʊd/', definition: 'n. 蟾蜍' },
  mode: { phonetic: '/məʊd/', definition: 'n. 模式' },
  code: { phonetic: '/kəʊd/', definition: 'n. 代码' },
  toed: { phonetic: '/təʊd/', definition: 'adj. 有趾的' },

  cute: { phonetic: '/kjuːt/', definition: 'adj. 可爱的' },
  cube: { phonetic: '/kjuːb/', definition: 'n. 立方体' },
  mute: { phonetic: '/mjuːt/', definition: 'adj. 静音的；v. 消音' },
  lute: { phonetic: '/luːt/', definition: 'n. 琵琶' },
  tube: { phonetic: '/tjuːb/', definition: 'n. 管子' },
  tune: { phonetic: '/tjuːn/', definition: 'n. 曲调' },
  dune: { phonetic: '/djuːn/', definition: 'n. 沙丘' },
  mule: { phonetic: '/mjuːl/', definition: 'n. 骡子' },
  rule: { phonetic: '/ruːl/', definition: 'n. 规则' },
  pure: { phonetic: '/pjʊə/', definition: 'adj. 纯净的' },
  cure: { phonetic: '/kjʊə/', definition: 'v. 治愈' },
  sure: { phonetic: '/ʃʊə/', definition: 'adj. 确定的' },
  blue: { phonetic: '/bluː/', definition: 'adj. 蓝色的' },
  glue: { phonetic: '/ɡluː/', definition: 'n. 胶水' },
  clue: { phonetic: '/kluː/', definition: 'n. 线索' },
  flue: { phonetic: '/fluː/', definition: 'n. 烟道' },
  true: { phonetic: '/truː/', definition: 'adj. 真的' },
  huge: { phonetic: '/hjuːdʒ/', definition: 'adj. 巨大的' },

  // Level 4
  black: { phonetic: '/blæk/', definition: 'adj. 黑色的；n. 黑色' },
  blue: { phonetic: '/bluː/', definition: 'adj. 蓝色的；n. 蓝色' },
  blond: { phonetic: '/blɒnd/', definition: 'adj. 金发的' },
  blink: { phonetic: '/blɪŋk/', definition: 'v. 眨眼' },
  block: { phonetic: '/blɒk/', definition: 'n. 块；街区' },
  bleed: { phonetic: '/bliːd/', definition: 'v. 流血' },
  bless: { phonetic: '/bles/', definition: 'v. 保佑' },
  blow: { phonetic: '/bləʊ/', definition: 'v. 吹' },
  bread: { phonetic: '/bred/', definition: 'n. 面包' },
  break: { phonetic: '/breɪk/', definition: 'v. 打破' },
  breed: { phonetic: '/briːd/', definition: 'v. 繁殖；n. 品种' },
  brick: { phonetic: '/brɪk/', definition: 'n. 砖块' },
  broom: { phonetic: '/bruːm/', definition: 'n. 扫帚' },
  bring: { phonetic: '/brɪŋ/', definition: 'v. 带来' },
  brown: { phonetic: '/braʊn/', definition: 'adj. 棕色的；n. 棕色' },
  crash: { phonetic: '/kræʃ/', definition: 'v. 撞碎' },
  crazy: { phonetic: '/ˈkreɪzi/', definition: 'adj. 疯狂的' },
  cross: { phonetic: '/krɒs/', definition: 'n. 十字；v. 穿过' },
  crow: { phonetic: '/krəʊ/', definition: 'n. 乌鸦' },
  crown: { phonetic: '/kraʊn/', definition: 'n. 王冠' },
  cry: { phonetic: '/kraɪ/', definition: 'v. 哭' },
  cry: { phonetic: '/kraɪ/', definition: 'n. 哭声' },
  cry: { phonetic: '/kraɪ/', definition: 'v. 叫喊（乌鸦）' },
  clock: { phonetic: '/klɒk/', definition: 'n. 时钟' },
  cloud: { phonetic: '/klaʊd/', definition: 'n. 云' },
  clown: { phonetic: '/klaʊn/', definition: 'n. 小丑' },
  clean: { phonetic: '/kliːn/', definition: 'adj. 干净的；v. 打扫' },
  class: { phonetic: '/klɑːs/', definition: 'n. 班级；课程' },
  clap: { phonetic: '/klæp/', definition: 'v. �鼓掌' },
  climb: { phonetic: '/klaɪm/', definition: 'v. 爬' },
  flag: { phonetic: '/flæɡ/', definition: 'n. 旗帜' },
  flat: { phonetic: '/flæt/', definition: 'adj. 平坦的；n. 公寓' },
  flood: { phonetic: '/flʌd/', definition: 'n. 洪水' },
  float: { phonetic: '/fləʊt/', definition: 'v. 漂浮' },
  floor: { phonetic: '/flɔː/', definition: 'n. 地板' },
  fly: { phonetic: '/flaɪ/', definition: 'v. 飞；n. 苍蝇' },
  flame: { phonetic: '/fleɪm/', definition: 'n. 火焰' },
  flake: { phonetic: '/fleɪk/', definition: 'n. 薄片' },
  frame: { phonetic: '/freɪm/', definition: 'n. 框架' },
  fresh: { phonetic: '/freʃ/', definition: 'adj. 新鲜的' },
  free: { phonetic: '/friː/', definition: 'adj. 自由的；免费的' },
  frog: { phonetic: '/frɒɡ/', definition: 'n. 青蛙' },
  front: { phonetic: '/frʌnt/', definition: 'n. 前面' },
  frost: { phonetic: '/frɒst/', definition: 'n. 霜' },
  fruit: { phonetic: '/fruːt/', definition: 'n. 水果' },
  bruise: { phonetic: '/bruːz/', definition: 'n. 瘀伤' },
  cruise: { phonetic: '/kruːz/', definition: 'n. 巡航；v. 巡游' },
  stew: { phonetic: '/stjuː/', definition: 'n. 炖菜' },
  grew: { phonetic: '/ɡruː/', definition: 'v. 生长（grow的过去式）' },
  glass: { phonetic: '/ɡlɑːs/', definition: 'n. 玻璃；眼镜' },
  glad: { phonetic: '/ɡlæd/', definition: 'adj. 高兴的' },
  glow: { phonetic: '/ɡləʊ/', definition: 'v. 发光' },
  globe: { phonetic: '/ɡləʊb/', definition: 'n. 地球仪' },
  glove: { phonetic: '/ɡlʌv/', definition: 'n. 手套' },
  glue: { phonetic: '/ɡluː/', definition: 'n. 胶水' },
  glide: { phonetic: '/ɡlaɪd/', definition: 'v. 滑行' },
  grain: { phonetic: '/ɡreɪn/', definition: 'n. 谷物' },
  grape: { phonetic: '/ɡreɪp/', definition: 'n. 葡萄' },
  graph: { phonetic: '/ɡrɑːf/', definition: 'n. 图表' },
  grass: { phonetic: '/ɡrɑːs/', definition: 'n. 草' },
  gray: { phonetic: '/ɡreɪ/', definition: 'adj. 灰色的；n. 灰色' },
  green: { phonetic: '/ɡriːn/', definition: 'adj. 绿色的；n. 绿色' },
  greet: { phonetic: '/ɡriːt/', definition: 'v. 问候' },
  grill: { phonetic: '/ɡrɪl/', definition: 'n. 烤架；v. 烧烤' },
  grow: { phonetic: '/ɡrəʊ/', definition: 'v. 生长' },
  grand: { phonetic: '/ɡrænd/', definition: 'adj. 宏伟的' },
  plum: { phonetic: '/plʌm/', definition: 'n. 李子' },
  plan: { phonetic: '/plæn/', definition: 'n. 计划；v. 规划' },
  play: { phonetic: '/pleɪ/', definition: 'v. 玩；n. 游戏' },
  place: { phonetic: '/pleɪs/', definition: 'n. 地方' },
  plane: { phonetic: '/pleɪn/', definition: 'n. 飞机' },
  plate: { phonetic: '/pleɪt/', definition: 'n. 盘子' },
  plant: { phonetic: '/plɑːnt/', definition: 'n. 植物；v. 种植' },
  plot: { phonetic: '/plɒt/', definition: 'n. 情节；小块土地' },
  plow: { phonetic: '/plaʊ/', definition: 'n. 犁' },
  pray: { phonetic: '/preɪ/', definition: 'v. 祈祷' },
  press: { phonetic: '/pres/', definition: 'v. 按；n. 新闻界' },
  prize: { phonetic: '/praɪz/', definition: 'n. 奖品' },
  proud: { phonetic: '/praʊd/', definition: 'adj. 骄傲的' },
  prove: { phonetic: '/pruːv/', definition: 'v. 证明' },
  sled: { phonetic: '/sled/', definition: 'n. 雪橇' },
  sleep: { phonetic: '/sliːp/', definition: 'v. 睡觉' },
  slice: { phonetic: '/slaɪs/', definition: 'n. 片；v. 切片' },
  slide: { phonetic: '/slaɪd/', definition: 'v. 滑动' },
  slow: { phonetic: '/sləʊ/', definition: 'adj. 慢的' },
  small: { phonetic: '/smɔːl/', definition: 'adj. 小的' },
  smell: { phonetic: '/smel/', definition: 'v. 闻；n. 气味' },
  smile: { phonetic: '/smaɪl/', definition: 'v. 微笑' },
  smoke: { phonetic: '/sməʊk/', definition: 'n. 烟；v. 抽烟' },
  snack: { phonetic: '/snæk/', definition: 'n. 零食' },
  snake: { phonetic: '/sneɪk/', definition: 'n. 蛇' },
  snow: { phonetic: '/snəʊ/', definition: 'n. 雪' },
  snail: { phonetic: '/sneɪl/', definition: 'n. 蜗牛' },
  speak: { phonetic: '/spiːk/', definition: 'v. 说话' },
  speed: { phonetic: '/spiːd/', definition: 'n. 速度' },
  spell: { phonetic: '/spel/', definition: 'v. 拼写' },
  spend: { phonetic: '/spend/', definition: 'v. 花费' },
  spill: { phonetic: '/spɪl/', definition: 'v. 溢出' },
  spin: { phonetic: '/spɪn/', definition: 'v. 旋转' },
  spoon: { phonetic: '/spuːn/', definition: 'n. 勺子' },
  sport: { phonetic: '/spɔːt/', definition: 'n. 运动' },
  spot: { phonetic: '/spɒt/', definition: 'n. 斑点；地点' },
  spread: { phonetic: '/spred/', definition: 'v. 传播' },
  spring: { phonetic: '/sprɪŋ/', definition: 'n. 春天；弹簧' },
  sprint: { phonetic: '/sprɪnt/', definition: 'v. 冲刺' },
  spray: { phonetic: '/spreɪ/', definition: 'v. 喷洒' },
  street: { phonetic: '/striːt/', definition: 'n. 街道' },
  stress: { phonetic: '/stres/', definition: 'n. 压力' },
  strike: { phonetic: '/straɪk/', definition: 'v. 打击；罢工' },
  strong: { phonetic: '/strɒŋ/', definition: 'adj. 强壮的' },
  string: { phonetic: '/strɪŋ/', definition: 'n. 绳子；字符串' },

  // Level 5
  shark: { phonetic: '/ʃɑːk/', definition: 'n. 鲨鱼' },
  shop: { phonetic: '/ʃɒp/', definition: 'n. 商店' },
  shut: { phonetic: '/ʃʌt/', definition: 'v. 关闭' },
  sheep: { phonetic: '/ʃiːp/', definition: 'n. 绵羊' },
  sheet: { phonetic: '/ʃiːt/', definition: 'n. 床单；纸张' },
  shell: { phonetic: '/ʃel/', definition: 'n. 贝壳' },
  shirt: { phonetic: '/ʃɜːt/', definition: 'n. 衬衫' },
  shine: { phonetic: '/ʃaɪn/', definition: 'v. 发光' },
  ship: { phonetic: '/ʃɪp/', definition: 'n. 船' },
  shock: { phonetic: '/ʃɒk/', definition: 'n. 震惊' },
  shoe: { phonetic: '/ʃuː/', definition: 'n. 鞋子' },
  shoot: { phonetic: '/ʃuːt/', definition: 'v. 射击' },
  short: { phonetic: '/ʃɔːt/', definition: 'adj. 短的' },
  shout: { phonetic: '/ʃaʊt/', definition: 'v. 大喊' },
  shape: { phonetic: '/ʃeɪp/', definition: 'n. 形状' },
  share: { phonetic: '/ʃeə/', definition: 'v. 分享' },
  shake: { phonetic: '/ʃeɪk/', definition: 'v. 摇动' },
  sharp: { phonetic: '/ʃɑːp/', definition: 'adj. 锋利的' },
  chef: { phonetic: '/ʃef/', definition: 'n. 厨师' },
  chant: { phonetic: '/tʃɑːnt/', definition: 'n. 吟唱' },
  charm: { phonetic: '/tʃɑːm/', definition: 'n. 魅力' },
  chart: { phonetic: '/tʃɑːt/', definition: 'n. 图表' },
  cheese: { phonetic: '/tʃiːz/', definition: 'n. 奶酪' },
  cheer: { phonetic: '/tʃɪə/', definition: 'v. 欢呼' },
  chess: { phonetic: '/tʃes/', definition: 'n. 国际象棋' },
  chest: { phonetic: '/tʃest/', definition: 'n. 胸部；箱子' },
  cheap: { phonetic: '/tʃiːp/', definition: 'adj. 便宜的' },
  child: { phonetic: '/tʃaɪld/', definition: 'n. 孩子' },
  chip: { phonetic: '/tʃɪp/', definition: 'n. 薯片；碎片' },
  chin: { phonetic: '/tʃɪn/', definition: 'n. 下巴' },
  choice: { phonetic: '/tʃɔɪs/', definition: 'n. 选择' },
  church: { phonetic: '/tʃɜːtʃ/', definition: 'n. 教堂' },
  match: { phonetic: '/mætʃ/', definition: 'n. 比赛；火柴；v. 匹配' },
  watch: { phonetic: '/wɒtʃ/', definition: 'n. 手表；v. 观看' },
  catch: { phonetic: '/kætʃ/', definition: 'v. 抓住' },
  patch: { phonetic: '/pætʃ/', definition: 'n. 补丁；v. 修补' },
  hatch: { phonetic: '/hætʃ/', definition: 'v. 孵化' },
  beach: { phonetic: '/biːtʃ/', definition: 'n. 海滩' },
  peach: { phonetic: '/piːtʃ/', definition: 'n. 桃子' },
  teach: { phonetic: '/tiːtʃ/', definition: 'v. 教' },
  reach: { phonetic: '/riːtʃ/', definition: 'v. 到达' },
  rich: { phonetic: '/rɪtʃ/', definition: 'adj. 富有的' },
  much: { phonetic: '/mʌtʃ/', definition: 'adj. 许多的；adv. 非常' },
  such: { phonetic: '/sʌtʃ/', definition: 'adj. 这样的' },
  lunch: { phonetic: '/lʌntʃ/', definition: 'n. 午餐' },
  bunch: { phonetic: '/bʌntʃ/', definition: 'n. 束；群' },
  touch: { phonetic: '/tʌtʃ/', definition: 'v. 触摸' },

  thorn: { phonetic: '/θɔːn/', definition: 'n. 刺' },
  think: { phonetic: '/θɪŋk/', definition: 'v. 思考' },
  thick: { phonetic: '/θɪk/', definition: 'adj. 厚的' },
  third: { phonetic: '/θɜːd/', definition: 'n. 第三；三分之一' },
  thumb: { phonetic: '/θʌm/', definition: 'n. 拇指' },
  three: { phonetic: '/θriː/', definition: 'n. 三' },
  throne: { phonetic: '/θrəʊn/', definition: 'n. 宝座' },
  throw: { phonetic: '/θrəʊ/', definition: 'v. 扔' },
  this: { phonetic: '/ðɪs/', definition: 'pron. 这个' },
  that: { phonetic: '/ðæt/', definition: 'pron. 那个' },
  these: { phonetic: '/ðiːz/', definition: 'pron. 这些' },
  those: { phonetic: '/ðəʊz/', definition: 'pron. 那些' },
  they: { phonetic: '/ðeɪ/', definition: 'pron. 他们' },
  them: { phonetic: '/ðem/', definition: 'pron. 他们（宾格）' },
  then: { phonetic: '/ðen/', definition: 'adv. 然后' },
  there: { phonetic: '/ðeə/', definition: 'adv. 那里' },
  their: { phonetic: '/ðeə/', definition: 'pron. 他们的' },
  brother: { phonetic: '/ˈbrʌðə/', definition: 'n. 兄弟' },
  mother: { phonetic: '/ˈmʌðə/', definition: 'n. 母亲' },
  father: { phonetic: '/ˈfɑːðə/', definition: 'n. 父亲' },
  feather: { phonetic: '/ˈfeðə/', definition: 'n. 羽毛' },
  leather: { phonetic: '/ˈleðə/', definition: 'n. 皮革' },
  weather: { phonetic: '/ˈweðə/', definition: 'n. 天气' },
  together: { phonetic: '/təˈɡeðə/', definition: 'adv. 一起' },
  another: { phonetic: '/əˈnʌðə/', definition: 'pron. 另一个' },
  rather: { phonetic: '/ˈrɑːðə/', definition: 'adv. 相当' },
  smooth: { phonetic: '/smuːð/', definition: 'adj. 光滑的' },
  tooth: { phonetic: '/tuːθ/', definition: 'n. 牙齿' },

  whale: { phonetic: '/weɪl/', definition: 'n. 鲸鱼' },
  wheel: { phonetic: '/wiːl/', definition: 'n. 轮子' },
  wheat: { phonetic: '/wiːt/', definition: 'n. 小麦' },
  white: { phonetic: '/waɪt/', definition: 'adj. 白色的；n. 白色' },
  what: { phonetic: '/wɒt/', definition: 'pron. 什么' },
  where: { phonetic: '/weə/', definition: 'pron. 哪里' },
  when: { phonetic: '/wen/', definition: 'pron. 什么时候' },
  who: { phonetic: '/huː/', definition: 'pron. 谁' },
  why: { phonetic: '/waɪ/', definition: 'pron. 为什么' },
  which: { phonetic: '/wɪtʃ/', definition: 'pron. 哪一个' },
  while: { phonetic: '/waɪl/', definition: 'conj. 当...时候' },
  whisper: { phonetic: '/ˈwɪspə/', definition: 'v. 耳语' },
  whistle: { phonetic: '/ˈwɪsl/', definition: 'n. 口哨；v. 吹口哨' },

  bird: { phonetic: '/bɜːd/', definition: 'n. 鸟' },
  girl: { phonetic: '/ɡɜːl/', definition: 'n. 女孩' },
  skirt: { phonetic: '/skɜːt/', definition: 'n. 裙子' },
  shirt: { phonetic: '/ʃɜːt/', definition: 'n. 衬衫' },
  first: { phonetic: '/fɜːst/', definition: 'n. 第一；adj. 第一的' },
  thirst: { phonetic: '/θɜːst/', definition: 'n. 口渴' },
  thirteen: { phonetic: '/ˌθɜːˈtiːn/', definition: 'n. 十三' },
  thirty: { phonetic: '/ˈθɜːti/', definition: 'n. 三十' },
  dirty: { phonetic: '/ˈdɜːti/', definition: 'adj. 脏的' },
  circle: { phonetic: '/ˈsɜːkl/', definition: 'n. 圆圈' },
  circus: { phonetic: '/ˈsɜːkəs/', definition: 'n. 马戏团' },
  nurse: { phonetic: '/nɜːs/', definition: 'n. 护士' },
  purse: { phonetic: '/pɜːs/', definition: 'n. 钱包' },
  curse: { phonetic: '/kɜːs/', definition: 'n. 诅咒' },
  hurt: { phonetic: '/hɜːt/', definition: 'v. 伤害' },
  burn: { phonetic: '/bɜːn/', definition: 'v. 燃烧' },
  turn: { phonetic: '/tɜːn/', definition: 'v. 转动' },
  curl: { phonetic: '/kɜːl/', definition: 'v. 卷曲' },
  surf: { phonetic: '/sɜːf/', definition: 'v. 冲浪' },
  turtle: { phonetic: '/ˈtɜːtl/', definition: 'n. 海龟' },

  star: { phonetic: '/stɑː/', definition: 'n. 星星' },
  start: { phonetic: '/stɑːt/', definition: 'v. 开始' },
  park: { phonetic: '/pɑːk/', definition: 'n. 公园；v. 停车' },
  dark: { phonetic: '/dɑːk/', definition: 'adj. 黑暗的' },
  mark: { phonetic: '/mɑːk/', definition: 'n. 标记；v. 做记号' },
  smart: { phonetic: '/smɑːt/', definition: 'adj. 聪明的' },
  spark: { phonetic: '/spɑːk/', definition: 'n. 火花' },
  farm: { phonetic: '/fɑːm/', definition: 'n. 农场' },
  arm: { phonetic: '/ɑːm/', definition: 'n. 手臂' },
  car: { phonetic: '/kɑː/', definition: 'n. 汽车' },
  far: { phonetic: '/fɑː/', definition: 'adj. 远的；adv. 远' },
  jar: { phonetic: '/dʒɑː/', definition: 'n. 罐子' },
  scarf: { phonetic: '/skɑːf/', definition: 'n. 围巾' },
  shark: { phonetic: '/ʃɑːk/', definition: 'n. 鲨鱼' },
  hard: { phonetic: '/hɑːd/', definition: 'adj. 硬的；困难的' },
  card: { phonetic: '/kɑːd/', definition: 'n. 卡片' },
  yard: { phonetic: '/jɑːd/', definition: 'n. 院子' },
  garden: { phonetic: '/ˈɡɑːdn/', definition: 'n. 花园' },
  party: { phonetic: '/ˈpɑːti/', definition: 'n. 派对' },
  march: { phonetic: '/mɑːtʃ/', definition: 'n. 三月；v. 行进' },
  barn: { phonetic: '/bɑːn/', definition: 'n. 谷仓' },

  boots: { phonetic: '/buːts/', definition: 'n. 靴子' },
  foot: { phonetic: '/fʊt/', definition: 'n. 脚' },
  room: { phonetic: '/ruːm/', definition: 'n. 房间' },
  moon: { phonetic: '/muːn/', definition: 'n. 月亮' },
  spoon: { phonetic: '/spuːn/', definition: 'n. 勺子' },
  zoo: { phonetic: '/zuː/', definition: 'n. 动物园' },
  food: { phonetic: '/fuːd/', definition: 'n. 食物' },
  mood: { phonetic: '/muːd/', definition: 'n. 情绪' },
  soon: { phonetic: '/suːn/', definition: 'adv. 很快' },
  noon: { phonetic: '/nuːn/', definition: 'n. 中午' },
  school: { phonetic: '/skuːl/', definition: 'n. 学校' },
  pool: { phonetic: '/puːl/', definition: 'n. 水池' },
  cool: { phonetic: '/kuːl/', definition: 'adj. 凉爽的；酷的' },
  tool: { phonetic: '/tuːl/', definition: 'n. 工具' },
  fool: { phonetic: '/fuːl/', definition: 'n. 傻瓜' },
  drool: { phonetic: '/druːl/', definition: 'v. 流口水' },
  stool: { phonetic: '/stuːl/', definition: 'n. 凳子' },
  shoot: { phonetic: '/ʃuːt/', definition: 'v. 射击' },
  root: { phonetic: '/ruːt/', definition: 'n. 根' },
  boot: { phonetic: '/buːt/', definition: 'n. 靴子' },
  book: { phonetic: '/bʊk/', definition: 'n. 书' },
  look: { phonetic: '/lʊk/', definition: 'v. 看' },
  cook: { phonetic: '/kʊk/', definition: 'v. 烹饪；n. 厨师' },
  hook: { phonetic: '/hʊk/', definition: 'n. 钩子' },
  took: { phonetic: '/tʊk/', definition: 'v. 拿（过去式）' },
  shook: { phonetic: '/ʃʊk/', definition: 'v. 摇（过去式）' },
  brook: { phonetic: '/brʊk/', definition: 'n. 小溪' },
  good: { phonetic: '/ɡʊd/', definition: 'adj. 好的' },
  wood: { phonetic: '/wʊd/', definition: 'n. 木头' },
  hood: { phonetic: '/hʊd/', definition: 'n. 兜帽' },
  stood: { phonetic: '/stʊd/', definition: 'v. 站（过去式）' },

  oy: { phonetic: '/ɔɪ/', definition: 'interj. 哎哟' },
  boy: { phonetic: '/bɔɪ/', definition: 'n. 男孩' },
  toy: { phonetic: '/tɔɪ/', definition: 'n. 玩具' },
  joy: { phonetic: '/dʒɔɪ/', definition: 'n. 快乐' },
  soy: { phonetic: '/sɔɪ/', definition: 'n. 大豆' },
  ahoy: { phonetic: '/əˈhɔɪ/', definition: 'interj. 啊哈' },
  royal: { phonetic: '/ˈrɔɪəl/', definition: 'adj. 皇家的' },

  coin: { phonetic: '/kɔɪn/', definition: 'n. 硬币' },
  join: { phonetic: '/dʒɔɪn/', definition: 'v. 加入' },
  oil: { phonetic: '/ɔɪl/', definition: 'n. 油' },
  boil: { phonetic: '/bɔɪl/', definition: 'v. 煮沸' },
  soil: { phonetic: '/sɔɪl/', definition: 'n. 土壤' },
  foil: { phonetic: '/fɔɪl/', definition: 'n. 箔纸' },
  coil: { phonetic: '/kɔɪl/', definition: 'n. 线圈' },
  broil: { phonetic: '/brɔɪl/', definition: 'v. 烤' },
  spoil: { phonetic: '/spɔɪl/', definition: 'v. 毁坏' },
  noisy: { phonetic: '/ˈnɔɪzi/', definition: 'adj. 嘈杂的' },

  cow: { phonetic: '/kaʊ/', definition: 'n. 奶牛' },
  clown: { phonetic: '/klaʊn/', definition: 'n. 小丑' },
  crown: { phonetic: '/kraʊn/', definition: 'n. 王冠' },
  down: { phonetic: '/daʊn/', definition: 'adv. 向下' },
  town: { phonetic: '/taʊn/', definition: 'n. 城镇' },
  brown: { phonetic: '/braʊn/', definition: 'adj. 棕色的；n. 棕色' },
  frown: { phonetic: '/fraʊn/', definition: 'v. 皱眉' },
  drown: { phonetic: '/draʊn/', definition: 'v. 淹死' },
  owl: { phonetic: '/aʊl/', definition: 'n. 猫头鹰' },
  bowl: { phonetic: '/bəʊl/', definition: 'n. 碗' },
  how: { phonetic: '/haʊ/', definition: 'adv. 怎样' },
  now: { phonetic: '/naʊ/', definition: 'adv. 现在' },
  cow: { phonetic: '/kaʊ/', definition: 'n. 奶牛' },
  wow: { phonetic: '/waʊ/', definition: 'interj. 哇' },
  scowl: { phonetic: '/skaʊl/', definition: 'v. 皱眉' },
  growl: { phonetic: '/ɡraʊl/', definition: 'v. 咆哮' },
  prowl: { phonetic: '/praʊl/', definition: 'v. 潜行' },

  // Level 1 exploreWords - 探索单词
  ax: { phonetic: '/æks/', definition: 'n. 斧头' },
  add: { phonetic: '/æd/', definition: 'v. 增加' },
  and: { phonetic: '/ænd/', definition: 'conj. 和' },
  arm: { phonetic: '/ɑːm/', definition: 'n. 手臂' },
  art: { phonetic: '/ɑːt/', definition: 'n. 艺术' },
  ask: { phonetic: '/ɑːsk/', definition: 'v. 问' },
  act: { phonetic: '/ækt/', definition: 'v. 行动' },
  age: { phonetic: '/eɪdʒ/', definition: 'n. 年龄' },
  
  book: { phonetic: '/bʊk/', definition: 'n. 书' },
  bus: { phonetic: '/bʌs/', definition: 'n. 公共汽车' },
  bed: { phonetic: '/bed/', definition: 'n. 床' },
  big: { phonetic: '/bɪɡ/', definition: 'adj. 大的' },
  bat: { phonetic: '/bæt/', definition: 'n. 球拍；蝙蝠' },
  bag: { phonetic: '/bæɡ/', definition: 'n. 包' },
  boy: { phonetic: '/bɔɪ/', definition: 'n. 男孩' },
  
  can: { phonetic: '/kæn/', definition: 'v. 能够；n. 罐头' },
  cap: { phonetic: '/kæp/', definition: 'n. 帽子' },
  cut: { phonetic: '/kʌt/', definition: 'v. 切' },
  coat: { phonetic: '/kəʊt/', definition: 'n. 外套' },
  corn: { phonetic: '/kɔːn/', definition: 'n. 玉米' },
  
  dad: { phonetic: '/dæd/', definition: 'n. 爸爸' },
  day: { phonetic: '/deɪ/', definition: 'n. 天；日子' },
  doll: { phonetic: '/dɒl/', definition: 'n. 玩偶' },
  dish: { phonetic: '/dɪʃ/', definition: 'n. 盘子' },
  desk: { phonetic: '/desk/', definition: 'n. 书桌' },
  dot: { phonetic: '/dɒt/', definition: 'n. 点' },
  
  eat: { phonetic: '/iːt/', definition: 'v. 吃' },
  end: { phonetic: '/end/', definition: 'n. 结束；v. 结束' },
  eye: { phonetic: '/aɪ/', definition: 'n. 眼睛' },
  elbow: { phonetic: '/ˈelbəʊ/', definition: 'n. 肘' },
  exit: { phonetic: '/ˈeksɪt/', definition: 'n. 出口' },
  edge: { phonetic: '/edʒ/', definition: 'n. 边缘' },
  even: { phonetic: '/ˈiːvən/', definition: 'adj. 平的；甚至' },
  every: { phonetic: '/ˈevri/', definition: 'adj. 每个' },
  
  fan: { phonetic: '/fæn/', definition: 'n. 扇子；风扇' },
  fox: { phonetic: '/fɒks/', definition: 'n. 狐狸' },
  fun: { phonetic: '/fʌn/', definition: 'n. 乐趣' },
  flag: { phonetic: '/flæɡ/', definition: 'n. 旗帜' },
  foot: { phonetic: '/fʊt/', definition: 'n. 脚' },
  five: { phonetic: '/faɪv/', definition: 'num. 五' },
  face: { phonetic: '/feɪs/', definition: 'n. 脸' },
  fast: { phonetic: '/fɑːst/', definition: 'adj. 快的' },
  
  girl: { phonetic: '/ɡɜːl/', definition: 'n. 女孩' },
  gas: { phonetic: '/ɡæs/', definition: 'n. 气体；汽油' },
  gap: { phonetic: '/ɡæp/', definition: 'n. 缺口' },
  gate: { phonetic: '/ɡeɪt/', definition: 'n. 大门' },
  game: { phonetic: '/ɡeɪm/', definition: 'n. 游戏' },
  get: { phonetic: '/ɡet/', definition: 'v. 得到' },
  go: { phonetic: '/ɡəʊ/', definition: 'v. 去' },
  good: { phonetic: '/ɡʊd/', definition: 'adj. 好的' },
  got: { phonetic: '/ɡɒt/', definition: 'v. 得到(get的过去式)' },
  
  hand: { phonetic: '/hænd/', definition: 'n. 手' },
  help: { phonetic: '/help/', definition: 'v. 帮助' },
  hen: { phonetic: '/hen/', definition: 'n. 母鸡' },
  hit: { phonetic: '/hɪt/', definition: 'v. 打' },
  hop: { phonetic: '/hɒp/', definition: 'v. 跳' },
  hot: { phonetic: '/hɒt/', definition: 'adj. 热的' },
  hug: { phonetic: '/hʌɡ/', definition: 'v. 拥抱' },
  ham: { phonetic: '/hæm/', definition: 'n. 火腿' },
  
  in: { phonetic: '/ɪn/', definition: 'prep. 在...里' },
  is: { phonetic: '/ɪz/', definition: 'v. 是' },
  it: { phonetic: '/ɪt/', definition: 'pron. 它' },
  if: { phonetic: '/ɪf/', definition: 'conj. 如果' },
  ill: { phonetic: '/ɪl/', definition: 'adj. 生病的' },
  inch: { phonetic: '/ɪntʃ/', definition: 'n. 英寸' },
  ice: { phonetic: '/aɪs/', definition: 'n. 冰' },
  into: { phonetic: '/ˈɪntuː/', definition: 'prep. 进入' },
  idea: { phonetic: '/aɪˈdɪə/', definition: 'n. 想法' },
  
  jet: { phonetic: '/dʒet/', definition: 'n. 喷气式飞机' },
  joy: { phonetic: '/dʒɔɪ/', definition: 'n. 快乐' },
  jar: { phonetic: '/dʒɑː/', definition: 'n. 罐子' },
  job: { phonetic: '/dʒɒb/', definition: 'n. 工作' },
  joke: { phonetic: '/dʒəʊk/', definition: 'n. 笑话' },
  just: { phonetic: '/dʒʌst/', definition: 'adv. 刚刚；只是' },
  jog: { phonetic: '/dʒɒɡ/', definition: 'v. 慢跑' },
  
  key: { phonetic: '/kiː/', definition: 'n. 钥匙' },
  kid: { phonetic: '/kɪd/', definition: 'n. 小孩' },
  kick: { phonetic: '/kɪk/', definition: 'v. 踢' },
  keep: { phonetic: '/kiːp/', definition: 'v. 保持' },
  kiss: { phonetic: '/kɪs/', definition: 'v. 吻' },
  kind: { phonetic: '/kaɪnd/', definition: 'adj. 善良的' },
  kit: { phonetic: '/kɪt/', definition: 'n. 工具箱' },
  knee: { phonetic: '/niː/', definition: 'n. 膝盖' },
  
  leg: { phonetic: '/leɡ/', definition: 'n. 腿' },
  lip: { phonetic: '/lɪp/', definition: 'n. 嘴唇' },
  log: { phonetic: '/lɒɡ/', definition: 'n. 原木' },
  lid: { phonetic: '/lɪd/', definition: 'n. 盖子' },
  let: { phonetic: '/let/', definition: 'v. 让' },
  lot: { phonetic: '/lɒt/', definition: 'n. 许多' },
  lap: { phonetic: '/læp/', definition: 'n. 大腿' },
  look: { phonetic: '/lʊk/', definition: 'v. 看' },
  
  man: { phonetic: '/mæn/', definition: 'n. 男人' },
  map: { phonetic: '/mæp/', definition: 'n. 地图' },
  mat: { phonetic: '/mæt/', definition: 'n. 垫子' },
  mom: { phonetic: '/mɒm/', definition: 'n. 妈妈' },
  mop: { phonetic: '/mɒp/', definition: 'n. 拖把' },
  met: { phonetic: '/met/', definition: 'v. 遇见(meet的过去式)' },
  mix: { phonetic: '/mɪks/', definition: 'v. 混合' },
  mud: { phonetic: '/mʌd/', definition: 'n. 泥' },
  
  nap: { phonetic: '/næp/', definition: 'n. 小睡' },
  not: { phonetic: '/nɒt/', definition: 'adv. 不' },
  nut: { phonetic: '/nʌt/', definition: 'n. 坚果' },
  new: { phonetic: '/njuː/', definition: 'adj. 新的' },
  nod: { phonetic: '/nɒd/', definition: 'v. 点头' },
  next: { phonetic: '/nekst/', definition: 'adj. 下一个' },
  
  ox: { phonetic: '/ɒks/', definition: 'n. 公牛' },
  on: { phonetic: '/ɒn/', definition: 'prep. 在...上' },
  odd: { phonetic: '/ɒd/', definition: 'adj. 奇怪的' },
  off: { phonetic: '/ɒf/', definition: 'prep. 离开' },
  old: { phonetic: '/əʊld/', definition: 'adj. 老的' },
  one: { phonetic: '/wʌn/', definition: 'num. 一' },
  open: { phonetic: '/ˈəʊpən/', definition: 'v. 打开' },
  over: { phonetic: '/ˈəʊvə/', definition: 'prep. 在...上方' },
  our: { phonetic: '/aʊə/', definition: 'pron. 我们的' },
  out: { phonetic: '/aʊt/', definition: 'adv. 出去' },
  
  pan: { phonetic: '/pæn/', definition: 'n. 平底锅' },
  pet: { phonetic: '/pet/', definition: 'n. 宠物' },
  pin: { phonetic: '/pɪn/', definition: 'n. 别针' },
  pot: { phonetic: '/pɒt/', definition: 'n. 锅' },
  pat: { phonetic: '/pæt/', definition: 'v. 轻拍' },
  peg: { phonetic: '/peɡ/', definition: 'n. 钉子' },
  put: { phonetic: '/pʊt/', definition: 'v. 放' },
  pack: { phonetic: '/pæk/', definition: 'v. 打包' },
  
  quick: { phonetic: '/kwɪk/', definition: 'adj. 快的' },
  quiet: { phonetic: '/ˈkwaɪət/', definition: 'adj. 安静的' },
  quit: { phonetic: '/kwɪt/', definition: 'v. 退出' },
  quiz: { phonetic: '/kwɪz/', definition: 'n. 测验' },
  quack: { phonetic: '/kwæk/', definition: 'v. 嘎嘎叫' },
  quest: { phonetic: '/kwest/', definition: 'n. 探索' },
  quote: { phonetic: '/kwəʊt/', definition: 'v. 引用' },
  quart: { phonetic: '/kwɔːt/', definition: 'n. 夸脱' },
  
  run: { phonetic: '/rʌn/', definition: 'v. 跑' },
  rat: { phonetic: '/ræt/', definition: 'n. 老鼠' },
  red: { phonetic: '/red/', definition: 'adj. 红色的' },
  rug: { phonetic: '/rʌɡ/', definition: 'n. 小地毯' },
  rain: { phonetic: '/reɪn/', definition: 'n. 雨' },
  road: { phonetic: '/rəʊd/', definition: 'n. 道路' },
  rock: { phonetic: '/rɒk/', definition: 'n. 岩石' },
  
  sit: { phonetic: '/sɪt/', definition: 'v. 坐' },
  sad: { phonetic: '/sæd/', definition: 'adj. 悲伤的' },
  sap: { phonetic: '/sæp/', definition: 'n. 树液' },
  sip: { phonetic: '/sɪp/', definition: 'v. 小口喝' },
  set: { phonetic: '/set/', definition: 'v. 设置' },
  sob: { phonetic: '/sɒb/', definition: 'v. 啜泣' },
  sod: { phonetic: '/sɒd/', definition: 'n. 草皮' },
  sub: { phonetic: '/sʌb/', definition: 'n. 潜艇；代替者' },
  
  tap: { phonetic: '/tæp/', definition: 'v. 轻拍' },
  tan: { phonetic: '/tæn/', definition: 'adj. 棕褐色的' },
  ten: { phonetic: '/ten/', definition: 'num. 十' },
  tip: { phonetic: '/tɪp/', definition: 'n. 尖端' },
  top: { phonetic: '/tɒp/', definition: 'n. 顶部' },
  tub: { phonetic: '/tʌb/', definition: 'n. 浴缸' },
  tag: { phonetic: '/tæɡ/', definition: 'n. 标签' },
  tin: { phonetic: '/tɪn/', definition: 'n. 锡' },
  
  under: { phonetic: '/ˈʌndə/', definition: 'prep. 在...下面' },
  until: { phonetic: '/ənˈtɪl/', definition: 'prep. 直到' },
  upset: { phonetic: '/ʌpˈset/', definition: 'adj. 沮丧的' },
  use: { phonetic: '/juːz/', definition: 'v. 使用' },
  ugly: { phonetic: '/ˈʌɡli/', definition: 'adj. 丑陋的' },
  undo: { phonetic: '/ʌnˈduː/', definition: 'v. 撤销' },
  uncle: { phonetic: '/ˈʌŋkl/', definition: 'n. 叔叔' },
  unit: { phonetic: '/ˈjuːnɪt/', definition: 'n. 单元' },
  
  van: { phonetic: '/væn/', definition: 'n. 面包车' },
  vase: { phonetic: '/vɑːz/', definition: 'n. 花瓶' },
  vet: { phonetic: '/vet/', definition: 'n. 兽医' },
  vest: { phonetic: '/vest/', definition: 'n. 背心' },
  vote: { phonetic: '/vəʊt/', definition: 'v. 投票' },
  voice: { phonetic: '/vɔɪs/', definition: 'n. 声音' },
  visit: { phonetic: '/ˈvɪzɪt/', definition: 'v. 拜访' },
  very: { phonetic: '/ˈveri/', definition: 'adv. 非常' },
  view: { phonetic: '/vjuː/', definition: 'n. 视野' },
  vine: { phonetic: '/vaɪn/', definition: 'n. 藤' },
  
  watch: { phonetic: '/wɒtʃ/', definition: 'v. 观看；n. 手表' },
  whale: { phonetic: '/weɪl/', definition: 'n. 鲸鱼' },
  window: { phonetic: '/ˈwɪndəʊ/', definition: 'n. 窗户' },
  wet: { phonetic: '/wet/', definition: 'adj. 湿的' },
  web: { phonetic: '/web/', definition: 'n. 网' },
  win: { phonetic: '/wɪn/', definition: 'v. 赢' },
  wig: { phonetic: '/wɪɡ/', definition: 'n. 假发' },
  wit: { phonetic: '/wɪt/', definition: 'n. 智慧' },
  wag: { phonetic: '/wæɡ/', definition: 'v. 摇摆' },
  wax: { phonetic: '/wæks/', definition: 'n. 蜡' },
  way: { phonetic: '/weɪ/', definition: 'n. 方式；道路' },
  
  box: { phonetic: '/bɒks/', definition: 'n. 盒子' },
  fix: { phonetic: '/fɪks/', definition: 'v. 修理' },
  max: { phonetic: '/mæks/', definition: 'n. 最大值' },
  tax: { phonetic: '/tæks/', definition: 'n. 税' },
  
  yellow: { phonetic: '/ˈjeləʊ/', definition: 'adj. 黄色的' },
  yak: { phonetic: '/jæk/', definition: 'n. 牦牛' },
  yoyo: { phonetic: '/ˈjəʊjəʊ/', definition: 'n. 溜溜球' },
  yes: { phonetic: '/jes/', definition: 'adv. 是的' },
  yet: { phonetic: '/jet/', definition: 'adv. 还' },
  yell: { phonetic: '/jel/', definition: 'v. 大喊' },
  yam: { phonetic: '/jæm/', definition: 'n. 山药' },
  yap: { phonetic: '/jæp/', definition: 'v. 狂吠' },
  yard: { phonetic: '/jɑːd/', definition: 'n. 院子' },
  yarn: { phonetic: '/jɑːn/', definition: 'n. 纱线' },
  yawn: { phonetic: '/jɔːn/', definition: 'v. 打哈欠' },
  
  zebra: { phonetic: '/ˈzebrə/', definition: 'n. 斑马' },
  zoo: { phonetic: '/zuː/', definition: 'n. 动物园' },
  zero: { phonetic: '/ˈzɪərəʊ/', definition: 'num. 零' },
  zap: { phonetic: '/zæp/', definition: 'v. 快速移动' },
  zip: { phonetic: '/zɪp/', definition: 'n. 拉链' },
  zone: { phonetic: '/zəʊn/', definition: 'n. 区域' },
  zoom: { phonetic: '/zuːm/', definition: 'v. 快速移动' },
  zest: { phonetic: '/zest/', definition: 'n. 热情' },
  zigzag: { phonetic: '/ˈzɪɡzæɡ/', definition: 'n. 之字形' },
  buzz: { phonetic: '/bʌz/', definition: 'v. 嗡嗡叫' }
};
